/*
 * File: app/view/CompanyPreferenceOption.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MobileBilling.view.CompanyPreferenceOption', {
    extend: 'Ext.container.Container',
    alias: 'widget.mdcompanypreferenceoption',

    requires: [
        'Ext.panel.Panel',
        'Ext.form.RadioGroup',
        'Ext.form.field.Radio',
        'Ext.form.field.Text'
    ],

    height: 442,
    width: 574,

    items: [
        {
            xtype: 'panel',
            itemId: 'tabConfiguration',
            title: 'Configuration',
            layout: {
                type: 'vbox',
                align: 'stretch'
            },
            items: [
                {
                    xtype: 'panel',
                    height: 237,
                    padding: 10,
                    bodyPadding: 5,
                    title: 'Report Header',
                    items: [
                        {
                            xtype: 'checkboxfield',
                            itemId: 'chkShowLogo',
                            fieldLabel: 'Show Logo',
                            labelWidth: 120,
                            boxLabel: '(This will show the Logo setup under System Manager on the upper left corner of the reports)'
                        },
                        {
                            xtype: 'radiogroup',
                            itemId: 'optCompanyContact',
                            width: 400,
                            fieldLabel: 'Company Contact',
                            labelWidth: 120,
                            layout: {
                                type: 'vbox',
                                align: 'stretch'
                            },
                            items: [
                                {
                                    xtype: 'radiofield',
                                    itemId: 'optLocationSpecific',
                                    boxLabel: 'Location Specific'
                                },
                                {
                                    xtype: 'textfield',
                                    flex: 1,
                                    itemId: 'txtCompanyName',
                                    padding: '0 0 0 20',
                                    fieldLabel: 'Company Name'
                                },
                                {
                                    xtype: 'radiofield',
                                    itemId: 'optCompanyWide',
                                    boxLabel: 'Company Wide'
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    padding: 10,
                    bodyPadding: 5,
                    title: 'Defaults',
                    items: [
                        {
                            xtype: 'textfield',
                            itemId: 'txtDefaultCustomerNo',
                            fieldLabel: 'Default New Customer No',
                            labelWidth: 180
                        },
                        {
                            xtype: 'textfield',
                            itemId: 'txtDefaultSiteNo',
                            fieldLabel: 'Default New Site No',
                            labelWidth: 180
                        },
                        {
                            xtype: 'textfield',
                            itemId: 'txtHazardousSpillCompanyName',
                            fieldLabel: 'Hazardous Spill Clean-up Company Name',
                            labelWidth: 180
                        },
                        {
                            xtype: 'textfield',
                            itemId: 'txtHazardousSpillCompanyPhoneNumber',
                            fieldLabel: 'Hazardous Spill Clean-up Company Phone Number',
                            labelWidth: 180
                        },
                        {
                            xtype: 'textfield',
                            itemId: 'txtEmergencyCustomerCode',
                            fieldLabel: 'Emergency Customer Code',
                            labelWidth: 180
                        }
                    ]
                }
            ]
        }
    ]

});