/*
 * File: app/view/Invoice.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MobileBilling.view.Invoice', {
    extend: 'Ext.window.Window',
    alias: 'widget.mdInvoice',

    requires: [
        'Ext.form.Panel',
        'Ext.tab.Panel',
        'Ext.tab.Tab',
        'Ext.form.field.ComboBox',
        'Ext.form.field.Date',
        'Ext.form.field.Number',
        'Ext.grid.Panel',
        'Ext.grid.column.Column',
        'Ext.view.Table',
        'Ext.grid.plugin.CellEditing',
        'Ext.selection.CheckboxModel',
        'Ext.toolbar.Paging'
    ],

    height: 655,
    hidden: false,
    minWidth: 1115,
    width: 1119,
    layout: 'fit',
    collapsible: true,
    title: 'Mobile Invoice',
    maximizable: true,

    items: [
        {
            xtype: 'form',
            flex: 1,
            itemId: 'frmShift',
            ui: 'i21-form',
            layout: 'fit',
            bodyPadding: 3,
            frameHeader: false,
            header: false,
            title: 'My Form',
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'top',
                    ui: 'i21-toolbar',
                    layout: {
                        type: 'hbox',
                        padding: '0 0 0 1'
                    },
                    items: [
                        {
                            xtype: 'button',
                            itemId: 'btnNew',
                            ui: 'i21-button-toolbar-small',
                            text: 'New'
                        },
                        {
                            xtype: 'button',
                            itemId: 'btnSave',
                            ui: 'i21-button-toolbar-small',
                            text: 'Save'
                        },
                        {
                            xtype: 'button',
                            itemId: 'btnDelete',
                            ui: 'i21-button-toolbar-small',
                            text: 'Delete'
                        },
                        {
                            xtype: 'button',
                            itemId: 'btnUndo',
                            ui: 'i21-button-toolbar-small',
                            text: 'Undo'
                        },
                        {
                            xtype: 'button',
                            itemId: 'btnPost',
                            ui: 'i21-button-toolbar-small',
                            text: 'Post'
                        },
                        {
                            xtype: 'button',
                            hidden: true,
                            itemId: 'btnUnpost',
                            ui: 'i21-button-toolbar-small',
                            text: 'Unpost'
                        },
                        {
                            xtype: 'button',
                            itemId: 'btnClose',
                            ui: 'i21-button-toolbar-small',
                            text: 'Close'
                        }
                    ]
                },
                {
                    xtype: 'ipagingstatusbar',
                    dock: 'bottom',
                    width: 360
                }
            ],
            items: [
                {
                    xtype: 'tabpanel',
                    itemId: 'tabShift',
                    bodyCls: 'i21-tab',
                    activeTab: 0,
                    plain: true,
                    items: [
                        {
                            xtype: 'panel',
                            itemId: 'pgeDetails',
                            bodyPadding: 5,
                            title: 'Details',
                            layout: {
                                type: 'vbox',
                                align: 'stretch'
                            },
                            items: [
                                {
                                    xtype: 'container',
                                    flex: 1,
                                    height: 200,
                                    layout: {
                                        type: 'hbox',
                                        align: 'stretch'
                                    },
                                    items: [
                                        {
                                            xtype: 'container',
                                            flex: 1,
                                            height: 158,
                                            minHeight: 100,
                                            width: 298,
                                            layout: {
                                                type: 'vbox',
                                                align: 'stretch'
                                            },
                                            items: [
                                                {
                                                    xtype: 'gridcombobox',
                                                    columns: [
                                                        {
                                                            xtype: 'gridcolumn',
                                                            dataIndex: 'intEntityId',
                                                            defaultSort: true,
                                                            hidden: true,
                                                            flex: 1
                                                        },
                                                        {
                                                            xtype: 'gridcolumn',
                                                            dataIndex: 'strName',
                                                            text: 'Customer Name',
                                                            flex: 1
                                                        },
                                                        {
                                                            xtype: 'gridcolumn',
                                                            dataIndex: 'strCustomerNumber',
                                                            text: 'Customer Number',
                                                            flex: 1
                                                        }
                                                    ],
                                                    lookUpField: true,
                                                    itemId: 'cboCustomer',
                                                    fieldLabel: 'Customer',
                                                    labelWidth: 110,
                                                    displayField: 'strCustomerNumber',
                                                    valueField: 'strCustomerNumber'
                                                },
                                                {
                                                    xtype: 'datefield',
                                                    itemId: 'dtpDeliveryDate',
                                                    fieldLabel: 'Delivery Date',
                                                    labelWidth: 110
                                                },
                                                {
                                                    xtype: 'numberfield',
                                                    itemId: 'txtInvoiceTotal',
                                                    fieldLabel: 'Invoice Total',
                                                    labelWidth: 110,
                                                    readOnly: true
                                                },
                                                {
                                                    xtype: 'gridcombobox',
                                                    columns: [
                                                        {
                                                            xtype: 'gridcolumn',
                                                            dataIndex: 'intPaymentMethodID',
                                                            defaultSort: true,
                                                            hidden: true,
                                                            flex: 1
                                                        },
                                                        {
                                                            xtype: 'gridcolumn',
                                                            dataIndex: 'strPaymentMethod',
                                                            text: 'Payment Method',
                                                            flex: 1
                                                        }
                                                    ],
                                                    lookUpField: true,
                                                    itemId: 'cboPaymentMethod',
                                                    fieldLabel: 'Payment Method',
                                                    labelWidth: 110,
                                                    readOnly: true,
                                                    displayField: 'strPaymentMethod',
                                                    valueField: 'intPaymentMethodId'
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'container',
                                            flex: 1,
                                            height: 100,
                                            minHeight: 100,
                                            padding: '0 0 0 10',
                                            layout: {
                                                type: 'vbox',
                                                align: 'stretch'
                                            },
                                            items: [
                                                {
                                                    xtype: 'gridcombobox',
                                                    columns: [
                                                        {
                                                            xtype: 'gridcolumn',
                                                            dataIndex: 'strLocationName',
                                                            text: 'Name',
                                                            flex: 1
                                                        },
                                                        {
                                                            xtype: 'gridcolumn',
                                                            dataIndex: 'intCompanyLocationId',
                                                            hidden: true
                                                        }
                                                    ],
                                                    dropDownField: true,
                                                    itemId: 'cboLocation',
                                                    fieldLabel: 'Location Name',
                                                    displayField: 'strLocationName',
                                                    valueField: 'strLocationName'
                                                },
                                                {
                                                    xtype: 'datefield',
                                                    itemId: 'dtpInvoiceDate',
                                                    fieldLabel: 'Invoice Date'
                                                },
                                                {
                                                    xtype: 'gridcombobox',
                                                    dropDownField: true,
                                                    columns: [
                                                        {
                                                            xtype: 'gridcolumn',
                                                            dataIndex: 'strTerm',
                                                            text: 'Term',
                                                            flex: 1
                                                        },
                                                        {
                                                            xtype: 'gridcolumn',
                                                            dataIndex: 'intTermID',
                                                            hidden: true
                                                        }
                                                    ],
                                                    itemId: 'cboTerm',
                                                    fieldLabel: 'Terms',
                                                    displayField: 'strTerm',
                                                    valueField: 'strTerm'
                                                },
                                                {
                                                    xtype: 'textfield',
                                                    itemId: 'txtPaymentInfo',
                                                    fieldLabel: 'Payment Info',
                                                    readOnly: true
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'container',
                                            flex: 1.8,
                                            height: 100,
                                            minHeight: 100,
                                            padding: '0 0 0 10',
                                            layout: {
                                                type: 'vbox',
                                                align: 'stretch'
                                            },
                                            items: [
                                                {
                                                    xtype: 'container',
                                                    layout: {
                                                        type: 'hbox',
                                                        align: 'stretch'
                                                    },
                                                    items: [
                                                        {
                                                            xtype: 'textfield',
                                                            flex: 1,
                                                            itemId: 'txtInvoiceNo',
                                                            fieldLabel: 'Invoice No'
                                                        },
                                                        {
                                                            xtype: 'gridcombobox',
                                                            dropDownField: true,
                                                            columns: [
                                                                {
                                                                    xtype: 'gridcolumn',
                                                                    dataIndex: 'strType',
                                                                    text: 'Type',
                                                                    flex: 1
                                                                }
                                                            ],
                                                            flex: 1,
                                                            itemId: 'cboType',
                                                            padding: '0 0 0 10',
                                                            fieldLabel: 'Type',
                                                            labelWidth: 80,
                                                            displayField: 'strType',
                                                            valueField: 'strType'
                                                        }
                                                    ]
                                                },
                                                {
                                                    xtype: 'container',
                                                    padding: '5 0 0 0',
                                                    layout: {
                                                        type: 'hbox',
                                                        align: 'stretch'
                                                    },
                                                    items: [
                                                        {
                                                            xtype: 'gridcombobox',
                                                            columns: [
                                                                {
                                                                    dataIndex: 'intEntityId',
                                                                    dataType: 'numeric',
                                                                    hidden: true
                                                                },
                                                                {
                                                                    dataIndex: 'strName',
                                                                    dataType: 'string',
                                                                    text: 'Driver Name',
                                                                    flex: 1
                                                                },
                                                                {
                                                                    dataIndex: 'strSalespersonId',
                                                                    dataType: 'string',
                                                                    text: 'Driver No',
                                                                    flex: .3
                                                                }
                                                            ],
                                                            dropDownField: true,
                                                            flex: 1,
                                                            itemId: 'cboDriver',
                                                            fieldLabel: 'Driver',
                                                            displayField: 'strName',
                                                            valueField: 'strName'
                                                        },
                                                        {
                                                            xtype: 'gridcombobox',
                                                            columns: [
                                                                {
                                                                    dataIndex: 'intShiftId',
                                                                    dataType: 'numeric',
                                                                    hidden: true
                                                                },
                                                                {
                                                                    dataIndex: 'intDriverId',
                                                                    dataType: 'numeric',
                                                                    hidden: true
                                                                },
                                                                {
                                                                    dataIndex: 'strShiftNo',
                                                                    dataType: 'string',
                                                                    text: 'Shift No',
                                                                    flex: 1
                                                                },
                                                                {
                                                                    xtype: 'datecolumn',
                                                                    dataIndex: 'dtmShiftDate',
                                                                    dataType: 'datetime',
                                                                    text: 'Shift Date',
                                                                    flex: 1
                                                                }
                                                            ],
                                                            dropDownField: true,
                                                            flex: 1,
                                                            itemId: 'cboShiftNo',
                                                            padding: '0 0 0 10',
                                                            fieldLabel: 'Shift No',
                                                            labelWidth: 80,
                                                            displayField: 'strShiftNo',
                                                            valueField: 'strShiftNo'
                                                        }
                                                    ]
                                                },
                                                {
                                                    xtype: 'textfield',
                                                    itemId: 'txtComments',
                                                    padding: '5 0 0 0',
                                                    fieldLabel: 'Comments'
                                                }
                                            ]
                                        }
                                    ]
                                },
                                {
                                    xtype: 'frmadvancesearchgrid',
                                    flex: 1,
                                    reference: 'grdInvoice',
                                    flex: 2,
                                    itemId: 'grdInvoice',
                                    padding: '0 0 20 0',
                                    frameHeader: false,
                                    header: false,
                                    title: 'My Grid Panel',
                                    columns: [
                                        {
                                            xtype: 'gridcolumn',
                                            flex: 0.9,
                                            itemId: 'colSiteNo',
                                            dataIndex: 'string',
                                            text: 'Site No',
                                            editor: {
                                                xtype: 'gridcombobox',
                                                dropDownField: true,
                                                columns: [
                                                    {
                                                        dataIndex: 'intSiteId',
                                                        dataType: 'numeric',
                                                        hidden: true
                                                    },
                                                    {
                                                        dataIndex: 'intLocationId',
                                                        dataType: 'numeric',
                                                        hidden: true
                                                    },
                                                    {
                                                        dataIndex: 'intSiteNumber',
                                                        dataType: 'string',
                                                        text: 'Site No',
                                                        flex: 1
                                                    },
                                                    {
                                                        dataIndex: 'strDescription',
                                                        dataType: 'string',
                                                        text: 'Site Description',
                                                        flex: 1
                                                    }
                                                ],
                                                itemId: 'cboSite',
                                                displayField: 'intSiteNumber',
                                                valueField: 'intSiteNumber'
                                            }
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            flex: 1,
                                            itemId: 'colSiteDescription',
                                            dataIndex: 'number',
                                            text: 'Description'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            flex: 1,
                                            itemId: 'colItemNo',
                                            dataIndex: 'date',
                                            text: 'Item',
                                            editor: {
                                                xtype: 'gridcombobox',
                                                lookUpField: true,
                                                columns: [
                                                    {
                                                        dataIndex: 'intItemId',
                                                        dataType: 'numeric',
                                                        hidden: true
                                                    },
                                                    {
                                                        dataIndex: 'intLocationId',
                                                        dataType: 'numeric',
                                                        hidden: true
                                                    },
                                                    {
                                                        dataIndex: 'strItemNo',
                                                        dataType: 'string',
                                                        text: 'Item No',
                                                        flex: 1
                                                    },
                                                    {
                                                        dataIndex: 'strItemDescription',
                                                        dataType: 'string',
                                                        text: 'Description',
                                                        flex: 1
                                                    }
                                                ],
                                                itemId: 'cboItem',
                                                displayField: 'strItemNo',
                                                valueField: 'strItemNo'
                                            }
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            flex: 1,
                                            itemId: 'colItemDescription',
                                            dataIndex: 'bool',
                                            text: 'Description'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            flex: 0.6,
                                            itemId: 'colPrice',
                                            width: 50,
                                            dataIndex: 'bool',
                                            text: 'Price',
                                            editor: {
                                                xtype: 'numberfield',
                                                itemId: 'EditPrice',
                                                fieldStyle: 'text-align: right',
                                                hideTrigger: true,
                                                minValue: 0
                                            }
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            flex: 0.6,
                                            itemId: 'colQty',
                                            dataIndex: 'bool',
                                            text: 'Qty',
                                            editor: {
                                                xtype: 'numberfield',
                                                itemId: 'editQty',
                                                fieldStyle: 'text-align: right',
                                                hideTrigger: true,
                                                minValue: 0
                                            }
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            flex: 0.8,
                                            itemId: 'colEndingPercent',
                                            dataIndex: 'bool',
                                            text: 'Ending %',
                                            editor: {
                                                xtype: 'numberfield',
                                                itemId: 'txtEndingPercent'
                                            }
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            flex: 0.8,
                                            itemId: 'colContract',
                                            width: 92,
                                            dataIndex: 'bool',
                                            text: 'Contract',
                                            editor: {
                                                xtype: 'gridcombobox',
                                                columns: [
                                                    {
                                                        dataIndex: 'strContractNumber',
                                                        dataType: 'string',
                                                        text: 'Contract',
                                                        flex: 1
                                                    },
                                                    {
                                                        dataIndex: 'strContractType',
                                                        dataType: 'string',
                                                        text: 'Type',
                                                        flex: 1
                                                    },
                                                    {
                                                        dataIndex: 'intContractSeq',
                                                        dataType: 'numeric',
                                                        hidden: true,
                                                        text: 'Seq',
                                                        flex: 1
                                                    },
                                                    {
                                                        dataIndex: 'strEntityName',
                                                        dataType: 'string',
                                                        hidden: true,
                                                        text: 'Customer',
                                                        flex: 1
                                                    },
                                                    {
                                                        dataIndex: 'strItemNo',
                                                        dataType: 'string',
                                                        hidden: true,
                                                        text: 'Item',
                                                        flex: 1
                                                    },
                                                    {
                                                        dataIndex: 'strLocationName',
                                                        dataType: 'string',
                                                        text: 'Location',
                                                        hidden: true,
                                                        flex: 0.5
                                                    },
                                                    {
                                                        dataIndex: 'strPricingType',
                                                        dataType: 'string',
                                                        text: 'Pricing Type',
                                                        flex: 0.5
                                                    },
                                                    {
                                                        dataIndex: 'dtmStartDate',
                                                        text: 'Start Date Time',
                                                        dataType: 'date',
                                                        format: 'm/d/Y H:i:s',
                                                        xtype: 'datecolumn',
                                                        flex: 1
                                                    },
                                                    {
                                                        dataIndex: 'dtmEndDate',
                                                        text: 'End Date Time',
                                                        dataType: 'date',
                                                        format: 'm/d/Y H:i:s',
                                                        xtype: 'datecolumn',
                                                        flex: 1
                                                    },
                                                    {
                                                        dataIndex: 'dblAvailableQty',
                                                        text: 'Available Units',
                                                        dataType: 'float',
                                                        flex: 1
                                                    },
                                                    {
                                                        dataIndex: 'dblCashPrice',
                                                        text: 'Contract Price',
                                                        dataType: 'float',
                                                        flex: 1
                                                    },
                                                    {
                                                        dataIndex: 'dblAdjustment',
                                                        text: 'Adjustment',
                                                        dataType: 'float',
                                                        flex: 1
                                                    }
                                                ],
                                                lookUpField: true,
                                                itemId: 'cboContract',
                                                displayField: 'strContractNumber',
                                                valueField: 'strContractNumber'
                                            }
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            flex: 1,
                                            itemId: 'colContractSequence',
                                            dataIndex: 'bool',
                                            text: 'Contract Seq'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            flex: 1,
                                            itemId: 'colPriceChanged',
                                            dataIndex: 'bool',
                                            text: 'Price Changed'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            flex: 1,
                                            itemId: 'colOrderNo',
                                            dataIndex: 'bool',
                                            text: 'Order No'
                                        }
                                    ],
                                    viewConfig: {
                                        height: 285
                                    },
                                    plugins: [
                                        {
                                            ptype: 'cellediting',
                                            pluginId: 'cepInvoice',
                                            clicksToEdit: 1
                                        }
                                    ],
                                    selModel: {
                                        selType: 'checkboxmodel'
                                    }
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            itemId: 'pgeAuditLog',
                            title: 'Audit Log',
                            items: [
                                {
                                    xtype: 'auditlogtree'
                                }
                            ]
                        }
                    ]
                }
            ]
        }
    ]

});