/*
 * File: app/view/Payment.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MobileBilling.view.Payment', {
    extend: 'Ext.window.Window',
    alias: 'widget.mdpayment',

    requires: [
        'Ext.form.Panel',
        'Ext.tab.Panel',
        'Ext.tab.Tab',
        'Ext.form.field.ComboBox',
        'Ext.form.field.Date',
        'Ext.form.field.Number',
        'Ext.form.field.TextArea',
        'Ext.toolbar.Paging'
    ],

    height: 470,
    hidden: false,
    minHeight: 470,
    minWidth: 670,
    width: 670,
    layout: 'fit',
    collapsible: true,
    title: 'Mobile Payment',
    maximizable: true,

    items: [
        {
            xtype: 'form',
            flex: 1,
            itemId: 'frmShift',
            ui: 'i21-form',
            layout: 'fit',
            bodyPadding: 3,
            frameHeader: false,
            header: false,
            title: 'My Form',
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'top',
                    ui: 'i21-toolbar',
                    layout: {
                        type: 'hbox',
                        padding: '0 0 0 1'
                    },
                    items: [
                        {
                            xtype: 'button',
                            itemId: 'btnNew',
                            ui: 'i21-button-toolbar-small',
                            text: 'New'
                        },
                        {
                            xtype: 'button',
                            itemId: 'btnSave',
                            ui: 'i21-button-toolbar-small',
                            text: 'Save'
                        },
                        {
                            xtype: 'button',
                            itemId: 'btnDelete',
                            ui: 'i21-button-toolbar-small',
                            text: 'Delete'
                        },
                        {
                            xtype: 'button',
                            itemId: 'btnUndo',
                            ui: 'i21-button-toolbar-small',
                            text: 'Undo'
                        },
                        {
                            xtype: 'button',
                            itemId: 'btnPost',
                            ui: 'i21-button-toolbar-small',
                            text: 'Post'
                        },
                        {
                            xtype: 'button',
                            itemId: 'btnClose',
                            ui: 'i21-button-toolbar-small',
                            text: 'Close'
                        }
                    ]
                },
                {
                    xtype: 'ipagingstatusbar',
                    dock: 'bottom',
                    width: 360
                }
            ],
            items: [
                {
                    xtype: 'tabpanel',
                    itemId: 'tabShift',
                    bodyCls: 'i21-tab',
                    activeTab: 0,
                    plain: true,
                    items: [
                        {
                            xtype: 'panel',
                            itemId: 'pgeDetails',
                            bodyPadding: 10,
                            title: 'Details',
                            layout: {
                                type: 'vbox',
                                align: 'stretch'
                            },
                            items: [
                                {
                                    xtype: 'container',
                                    padding: '0 0 10 0',
                                    layout: {
                                        type: 'hbox',
                                        align: 'stretch'
                                    },
                                    items: [
                                        {
                                            xtype: 'gridcombobox',
                                            lookUpField: true,
                                            columns: [
                                                {
                                                    xtype: 'gridcolumn',
                                                    dataIndex: 'intEntityId',
                                                    defaultSort: true,
                                                    hidden: true,
                                                    flex: 1
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    dataIndex: 'strName',
                                                    text: 'Customer Name',
                                                    flex: 1
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    dataIndex: 'strCustomerNumber',
                                                    text: 'Customer Number',
                                                    flex: 1
                                                }
                                            ],
                                            flex: 1,
                                            itemId: 'cboCustomer',
                                            padding: '',
                                            fieldLabel: 'Customer',
                                            displayField: 'strName',
                                            valueField: 'strName'
                                        },
                                        {
                                            xtype: 'gridcombobox',
                                            columns: [
                                                {
                                                    xtype: 'gridcolumn',
                                                    dataIndex: 'strLocationName',
                                                    text: 'Name',
                                                    flex: 1
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    dataIndex: 'intCompanyLocationId',
                                                    hidden: true
                                                }
                                            ],
                                            dropDownField: true,
                                            flex: 1,
                                            itemId: 'cboLocation',
                                            padding: '0 0 0 10',
                                            fieldLabel: 'Location Name',
                                            displayField: 'strLocationName',
                                            valueField: 'strLocationName'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'container',
                                    padding: '0 0 10 0',
                                    layout: {
                                        type: 'hbox',
                                        align: 'stretch'
                                    },
                                    items: [
                                        {
                                            xtype: 'gridcombobox',
                                            columns: [
                                                {
                                                    dataIndex: 'intEntityId',
                                                    dataType: 'numeric',
                                                    hidden: true
                                                },
                                                {
                                                    dataIndex: 'strSalespersonId',
                                                    dataType: 'string',
                                                    text: 'Driver No',
                                                    flex: .3
                                                },
                                                {
                                                    dataIndex: 'strName',
                                                    dataType: 'string',
                                                    text: 'Driver Name',
                                                    flex: 1
                                                }
                                            ],
                                            dropDownField: true,
                                            flex: 1,
                                            itemId: 'cboDriver',
                                            fieldLabel: 'Driver',
                                            displayField: 'strSalespersonId',
                                            valueField: 'strSalespersonId'
                                        },
                                        {
                                            xtype: 'textfield',
                                            flex: 1,
                                            itemId: 'txtDriverName',
                                            padding: '0 0 0 10',
                                            fieldLabel: 'Driver Name',
                                            readOnly: true
                                        }
                                    ]
                                },
                                {
                                    xtype: 'container',
                                    padding: '0 0 10 0',
                                    layout: {
                                        type: 'hbox',
                                        align: 'stretch'
                                    },
                                    items: [
                                        {
                                            xtype: 'textfield',
                                            flex: 1,
                                            itemId: 'txtPaymentNo',
                                            fieldLabel: 'Payment No'
                                        },
                                        {
                                            xtype: 'gridcombobox',
                                            columns: [
                                                {
                                                    dataIndex: 'intShiftId',
                                                    dataType: 'numeric',
                                                    hidden: true
                                                },
                                                {
                                                    dataIndex: 'intDriverId',
                                                    dataType: 'numeric',
                                                    hidden: true
                                                },
                                                {
                                                    dataIndex: 'intShiftNumber',
                                                    dataType: 'numeric',
                                                    text: 'Shift No',
                                                    flex: 1
                                                },
                                                {
                                                    xtype: 'datecolumn',
                                                    dataIndex: 'dtmShiftDate',
                                                    dataType: 'date',
                                                    text: 'Shift Date',
                                                    flex: 1
                                                }
                                            ],
                                            dropDownField: true,
                                            flex: 1,
                                            itemId: 'cboShiftNo',
                                            padding: '0 0 0 10',
                                            fieldLabel: 'Shift No',
                                            displayField: 'intShiftNumber',
                                            valueField: 'intShiftNumber'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'container',
                                    padding: '0 0 10 0',
                                    layout: {
                                        type: 'hbox',
                                        align: 'stretch'
                                    },
                                    items: [
                                        {
                                            xtype: 'datefield',
                                            flex: 1,
                                            itemId: 'dtpPaymentDate',
                                            fieldLabel: 'Payment Date'
                                        },
                                        {
                                            xtype: 'gridcombobox',
                                            columns: [
                                                {
                                                    dataIndex: 'strMethod',
                                                    dataType: 'string',
                                                    text: 'Payment Method',
                                                    flex: 1
                                                }
                                            ],
                                            dropDownField: true,
                                            flex: 1,
                                            itemId: 'cboPaymentMethod',
                                            padding: '0 0 0 10',
                                            fieldLabel: 'Method',
                                            displayField: 'strMethod',
                                            valueField: 'strMethod'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'container',
                                    padding: '0 0 10 0',
                                    layout: {
                                        type: 'hbox',
                                        align: 'stretch'
                                    },
                                    items: [
                                        {
                                            xtype: 'textfield',
                                            flex: 1,
                                            itemId: 'txtCheckNo',
                                            padding: '',
                                            fieldLabel: 'Check No'
                                        },
                                        {
                                            xtype: 'numberfield',
                                            flex: 1,
                                            itemId: 'txtAmount',
                                            padding: '0 0 0 10',
                                            fieldLabel: 'Amount'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'container',
                                    flex: 1,
                                    minWidth: 610,
                                    width: 610,
                                    layout: 'card',
                                    items: [
                                        {
                                            xtype: 'textareafield',
                                            flex: 1,
                                            itemId: 'txtComments',
                                            minWidth: 600,
                                            width: 600,
                                            fieldLabel: 'Comments'
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            itemId: 'pgeAuditLog',
                            title: 'Audit Log',
                            items: [
                                {
                                    xtype: 'auditlogtree'
                                }
                            ]
                        }
                    ]
                }
            ]
        }
    ]

});