/*
 * File: app/view/Shift.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MobileBilling.view.Shift', {
    extend: 'Ext.window.Window',
    alias: 'widget.mdshift',

    requires: [
        'Ext.form.Panel',
        'Ext.tab.Panel',
        'Ext.tab.Tab',
        'Ext.form.field.Date',
        'Ext.form.field.Time',
        'Ext.form.field.Number',
        'Ext.grid.Panel',
        'Ext.grid.column.Date',
        'Ext.grid.column.Number',
        'Ext.grid.column.Check',
        'Ext.view.Table',
        'Ext.toolbar.Paging'
    ],

    height: 759,
    hidden: false,
    width: 955,
    layout: 'fit',
    collapsible: true,
    title: 'Shift',
    maximizable: true,

    items: [
        {
            xtype: 'form',
            flex: 1,
            itemId: 'frmShift',
            ui: 'i21-form',
            layout: 'fit',
            bodyPadding: 3,
            frameHeader: false,
            header: false,
            title: 'My Form',
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'top',
                    ui: 'i21-toolbar',
                    layout: {
                        type: 'hbox',
                        padding: '0 0 0 1'
                    },
                    items: [
                        {
                            xtype: 'button',
                            itemId: 'btnNew',
                            ui: 'i21-button-toolbar-small',
                            text: 'New'
                        },
                        {
                            xtype: 'button',
                            itemId: 'btnSave',
                            ui: 'i21-button-toolbar-small',
                            text: 'Save'
                        },
                        {
                            xtype: 'button',
                            itemId: 'btnDelete',
                            ui: 'i21-button-toolbar-small',
                            text: 'Delete'
                        },
                        {
                            xtype: 'button',
                            itemId: 'btnUndo',
                            ui: 'i21-button-toolbar-small',
                            text: 'Undo'
                        },
                        {
                            xtype: 'button',
                            itemId: 'btnClose',
                            ui: 'i21-button-toolbar-small',
                            text: 'Close'
                        }
                    ]
                },
                {
                    xtype: 'ipagingstatusbar',
                    dock: 'bottom',
                    width: 360
                }
            ],
            items: [
                {
                    xtype: 'tabpanel',
                    itemId: 'tabShift',
                    bodyCls: 'i21-tab',
                    activeTab: 0,
                    plain: true,
                    items: [
                        {
                            xtype: 'panel',
                            itemId: 'pgeDetails',
                            bodyPadding: 5,
                            title: 'Details',
                            layout: {
                                type: 'vbox',
                                align: 'stretch'
                            },
                            items: [
                                {
                                    xtype: 'container',
                                    layout: {
                                        type: 'hbox',
                                        align: 'stretchmax',
                                        padding: '0 0 10 0'
                                    },
                                    items: [
                                        {
                                            xtype: 'datefield',
                                            flex: 1,
                                            itemId: 'dtpShiftDate',
                                            padding: '',
                                            fieldLabel: 'Date',
                                            readOnly: true
                                        },
                                        {
                                            xtype: 'textfield',
                                            flex: 1,
                                            itemId: 'txtDriverNumber',
                                            padding: '0 0 0 10',
                                            fieldLabel: 'Driver No',
                                            readOnly: true
                                        },
                                        {
                                            xtype: 'textfield',
                                            flex: 1,
                                            itemId: 'txtDriverName',
                                            padding: '0 0 0 10',
                                            fieldLabel: 'Driver Name',
                                            readOnly: true
                                        },
                                        {
                                            xtype: 'textfield',
                                            flex: 1,
                                            itemId: 'txtLocationName',
                                            padding: '0 0 0 10',
                                            fieldLabel: 'Location Name',
                                            readOnly: true
                                        }
                                    ]
                                },
                                {
                                    xtype: 'container',
                                    layout: {
                                        type: 'hbox',
                                        align: 'stretchmax',
                                        padding: '0 0 10 0'
                                    },
                                    items: [
                                        {
                                            xtype: 'textfield',
                                            flex: 1,
                                            itemId: 'txtShiftNo',
                                            fieldLabel: 'Shift No',
                                            readOnly: true
                                        },
                                        {
                                            xtype: 'timefield',
                                            flex: 1,
                                            itemId: 'dtpStartTime',
                                            padding: '0 0 0 10',
                                            fieldLabel: 'Start Time',
                                            readOnly: true
                                        },
                                        {
                                            xtype: 'timefield',
                                            flex: 1,
                                            itemId: 'dtpEndTime',
                                            padding: '0 0 0 10',
                                            fieldLabel: 'End Time',
                                            readOnly: true
                                        },
                                        {
                                            xtype: 'textfield',
                                            flex: 1,
                                            itemId: 'txtTruckNo',
                                            padding: '0 0 0 10',
                                            fieldLabel: 'Truck No',
                                            readOnly: true
                                        }
                                    ]
                                },
                                {
                                    xtype: 'container',
                                    layout: {
                                        type: 'hbox',
                                        align: 'stretchmax',
                                        padding: '0 0 10 0'
                                    },
                                    items: [
                                        {
                                            xtype: 'numberfield',
                                            flex: 1,
                                            itemId: 'txtStartOdometer',
                                            padding: '',
                                            fieldLabel: 'Start Odometer',
                                            readOnly: true
                                        },
                                        {
                                            xtype: 'numberfield',
                                            flex: 1,
                                            itemId: 'txtEndOdometer',
                                            padding: '0 0 0 10',
                                            fieldLabel: 'End Odometer',
                                            readOnly: true
                                        },
                                        {
                                            xtype: 'numberfield',
                                            flex: 1,
                                            itemId: 'txtFuelDelivered',
                                            padding: '0 0 0 10',
                                            fieldLabel: 'Fuel Delivered',
                                            readOnly: true
                                        },
                                        {
                                            xtype: 'numberfield',
                                            flex: 1,
                                            itemId: 'txtFuelSales',
                                            padding: '0 0 0 10',
                                            fieldLabel: 'Fuel Sales',
                                            readOnly: true
                                        }
                                    ]
                                },
                                {
                                    xtype: 'tabpanel',
                                    flex: 1,
                                    itemId: 'tabTransactions',
                                    activeTab: 0,
                                    items: [
                                        {
                                            xtype: 'panel',
                                            itemId: 'pgeInvoices',
                                            bodyPadding: 5,
                                            title: 'Invoices',
                                            layout: {
                                                type: 'vbox',
                                                align: 'stretch'
                                            },
                                            items: [
                                                {
                                                    xtype: 'combobox',
                                                    itemId: 'cboFilterInvoice',
                                                    fieldLabel: 'Show'
                                                },
                                                {
                                                    xtype: 'frmadvancesearchgrid',
                                                    reference: 'grdInvoice',
                                                    flex: 2,
                                                    itemId: 'grdInvoice',
                                                    padding: '0 0 20 0',
                                                    frameHeader: false,
                                                    header: false,
                                                    title: 'My Grid Panel',
                                                    columns: [
                                                        {
                                                            xtype: 'gridcolumn',
                                                            flex: 1,
                                                            itemId: 'colCustomer',
                                                            dataIndex: 'string',
                                                            text: 'Customer'
                                                        },
                                                        {
                                                            xtype: 'gridcolumn',
                                                            flex: 1,
                                                            itemId: 'colLocation',
                                                            dataIndex: 'number',
                                                            text: 'Location'
                                                        },
                                                        {
                                                            xtype: 'gridcolumn',
                                                            flex: 0.8,
                                                            itemId: 'colInvoiceNo',
                                                            dataIndex: 'date',
                                                            text: 'Invoice No'
                                                        },
                                                        {
                                                            xtype: 'datecolumn',
                                                            flex: 0.8,
                                                            itemId: 'colInvoiceDate',
                                                            dataIndex: 'bool',
                                                            text: 'Invoice Date'
                                                        },
                                                        {
                                                            xtype: 'gridcolumn',
                                                            flex: 0.8,
                                                            itemId: 'colType',
                                                            dataIndex: 'bool',
                                                            text: 'Type'
                                                        },
                                                        {
                                                            xtype: 'gridcolumn',
                                                            flex: 0.8,
                                                            itemId: 'colTerms',
                                                            dataIndex: 'bool',
                                                            text: 'Terms'
                                                        },
                                                        {
                                                            xtype: 'numbercolumn',
                                                            flex: 1,
                                                            itemId: 'colInvoiceTotal',
                                                            dataIndex: 'bool',
                                                            text: 'Invoice Total'
                                                        },
                                                        {
                                                            xtype: 'gridcolumn',
                                                            flex: 1,
                                                            itemId: 'colComment',
                                                            dataIndex: 'bool',
                                                            text: 'Comments'
                                                        },
                                                        {
                                                            xtype: 'checkcolumn',
                                                            disabled: true,
                                                            flex: 0.5,
                                                            itemId: 'colPosted',
                                                            dataIndex: 'bool',
                                                            text: 'Posted'
                                                        },
                                                        {
                                                            xtype: 'checkcolumn',
                                                            disabled: true,
                                                            flex: 0.5,
                                                            itemId: 'colVoided',
                                                            dataIndex: 'bool',
                                                            text: 'Voided'
                                                        }
                                                    ]
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'panel',
                                            itemId: 'pgePayment',
                                            bodyPadding: 5,
                                            title: 'Payment',
                                            layout: {
                                                type: 'vbox',
                                                align: 'stretch'
                                            },
                                            items: [
                                                {
                                                    xtype: 'combobox',
                                                    itemId: 'cboFilterPayment',
                                                    fieldLabel: 'Show'
                                                },
                                                {
                                                    xtype: 'frmadvancesearchgrid',
                                                    reference: 'grdPayment',
                                                    flex: 2,
                                                    itemId: 'grdPayment',
                                                    padding: '0 0 20 0',
                                                    frameHeader: false,
                                                    header: false,
                                                    title: 'My Grid Panel',
                                                    columns: [
                                                        {
                                                            xtype: 'gridcolumn',
                                                            flex: 1,
                                                            itemId: 'colCustomer',
                                                            dataIndex: 'string',
                                                            text: 'Customer'
                                                        },
                                                        {
                                                            xtype: 'gridcolumn',
                                                            flex: 1,
                                                            itemId: 'colLocation',
                                                            dataIndex: 'number',
                                                            text: 'Location'
                                                        },
                                                        {
                                                            xtype: 'gridcolumn',
                                                            flex: 0.8,
                                                            itemId: 'colPaymentNo',
                                                            dataIndex: 'date',
                                                            text: 'Payment No'
                                                        },
                                                        {
                                                            xtype: 'datecolumn',
                                                            flex: 0.8,
                                                            itemId: 'colPaymentDate',
                                                            dataIndex: 'bool',
                                                            text: 'Payment Date'
                                                        },
                                                        {
                                                            xtype: 'gridcolumn',
                                                            flex: 0.8,
                                                            itemId: 'colMethod',
                                                            dataIndex: 'bool',
                                                            text: 'Method'
                                                        },
                                                        {
                                                            xtype: 'gridcolumn',
                                                            flex: 0.8,
                                                            itemId: 'colCheckNumber',
                                                            dataIndex: 'bool',
                                                            text: 'Check Number'
                                                        },
                                                        {
                                                            xtype: 'numbercolumn',
                                                            flex: 1,
                                                            itemId: 'colPayment',
                                                            dataIndex: 'bool',
                                                            text: 'Payment'
                                                        },
                                                        {
                                                            xtype: 'gridcolumn',
                                                            flex: 1,
                                                            itemId: 'colComment',
                                                            dataIndex: 'bool',
                                                            text: 'Comments'
                                                        },
                                                        {
                                                            xtype: 'checkcolumn',
                                                            disabled: true,
                                                            flex: 0.5,
                                                            itemId: 'colPosted',
                                                            dataIndex: 'bool',
                                                            text: 'Posted'
                                                        },
                                                        {
                                                            xtype: 'checkcolumn',
                                                            disabled: true,
                                                            flex: 0.5,
                                                            itemId: 'colVoided',
                                                            dataIndex: 'bool',
                                                            text: 'Voided'
                                                        }
                                                    ]
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            itemId: 'pgeAuditLog',
                            title: 'Audit Log',
                            items: [
                                {
                                    xtype: 'auditlogtree'
                                }
                            ]
                        }
                    ]
                }
            ]
        }
    ]

});