Ext.define("MobileBilling.search.Invoice", {
    alias: "search.mdinvoice",
    singleton: true,
    searchConfigs: [
       {
            title: 'Search Mobile Invoices',
            url: './mobilebilling/api/invoice/search',
            columns: [
                {dataIndex: 'intInvoiceId', text: 'Invoice Id', flex: 1, defaultSort: true, dataType: 'numeric', key: true, hidden: true},
                {dataIndex: 'strInvoiceNo', text: 'Invoice No', flex: 1, dataType: 'string' },
                {dataIndex: 'intOrderId', text: 'Order Id', flex: 1, dataType: 'numeric', hidden: true },
                {dataIndex: 'intEntityCustomerId', text: 'Customer Id', flex: 1, dataType: 'numeric', hidden: true },
                {dataIndex: 'strCustomerNo', text: 'Customer No', flex: 1, dataType: 'string' },
                {dataIndex: 'strCustomerName', text: 'Customer Name', flex: 1, dataType: 'string' },
                {dataIndex: 'intLocationId', text: 'Location Id', flex: 1, dataType: 'numeric', hidden: true },
                {dataIndex: 'strLocationName', text: 'Location Name', flex: 1, dataType: 'string' },
                {dataIndex: 'strType', text: 'Invoice Type', flex: 1, dataType: 'string' },
                {dataIndex: 'dtmDeliveryDate', text: 'Delivery Date', flex: 1, dataType: 'date' },
                {dataIndex: 'dtmInvoiceDate', text: 'Invoice Date', flex: 1, dataType: 'date' },
                {dataIndex: 'intDriverId', text: 'Driver Id', flex: 1, dataType: 'numeric', hidden: true },
                {dataIndex: 'strDriverNo', text: 'Driver No', flex: 1, dataType: 'string' },
                {dataIndex: 'strDriverName', text: 'Driver Name', flex: 1, dataType: 'string' },
                {dataIndex: 'intShiftId', text: 'Shift Id', flex: 1, dataType: 'numeric', hidden: true },
                {dataIndex: 'intShiftNumber', text: 'Shift No', flex: 1, dataType: 'numeric' },
                {dataIndex: 'strShiftNo', text: 'Shift Id', flex: 1, dataType: 'string', hidden: true },
                {dataIndex: 'strComments', text: 'Comments', flex: 1, dataType: 'string' },
                {dataIndex: 'dblTotal', text: 'Total', flex: 1, dataType: 'float' , xtype: 'numbercolumn', currencyField: true},
                {dataIndex: 'intTermId', text: 'Term Id', flex: 1, dataType: 'numeric', hidden: true },
                {dataIndex: 'ysnPosted', text: 'Posted', flex: 1, dataType: 'boolean' },
                {dataIndex: 'ysnVoided', text: 'Voided', flex: 1, dataType: 'boolean' },
            ]
        },
        {
            title: 'Search Mobile Invoice Items',
            url: './mobilebilling/api/invoice/searchitems',
            columns: [
                {dataIndex: 'intInvoiceId', text: 'Invoice Id', flex: 1, defaultSort: true, dataType: 'numeric', key: true, hidden: true},
                {dataIndex: 'strInvoiceNo', text: 'Invoice No', flex: 1, dataType: 'string' },
                {dataIndex: 'intOrderId', text: 'Order Id', flex: 1, dataType: 'numeric', hidden: true },
                {dataIndex: 'intEntityCustomerId', text: 'Customer Id', flex: 1, dataType: 'numeric', hidden: true },
                {dataIndex: 'strCustomerNo', text: 'Customer No', flex: 1, dataType: 'string' },
                {dataIndex: 'strCustomerName', text: 'Customer Name', flex: 1, dataType: 'string' },
                {dataIndex: 'intLocationId', text: 'Location Id', flex: 1, dataType: 'numeric', hidden: true },
                {dataIndex: 'strLocationName', text: 'Location Name', flex: 1, dataType: 'string' },
                {dataIndex: 'strType', text: 'Invoice Type', flex: 1, dataType: 'string' },
                {dataIndex: 'dtmDeliveryDate', text: 'Delivery Date', flex: 1, dataType: 'date' },
                {dataIndex: 'dtmInvoiceDate', text: 'Invoice Date', flex: 1, dataType: 'date' },
                {dataIndex: 'intDriverId', text: 'Driver Id', flex: 1, dataType: 'numeric', hidden: true },
                {dataIndex: 'strDriverNo', text: 'Driver No', flex: 1, dataType: 'string' },
                {dataIndex: 'strDriverName', text: 'Driver Name', flex: 1, dataType: 'string' },
                {dataIndex: 'intShiftId', text: 'Shift Id', flex: 1, dataType: 'numeric', hidden: true },
                {dataIndex: 'intShiftNumber', text: 'Shift No', flex: 1, dataType: 'numeric' },
                {dataIndex: 'strShiftNo', text: 'Shift Id', flex: 1, dataType: 'string', hidden: true },
                {dataIndex: 'strComments', text: 'Comments', flex: 1, dataType: 'string' },
                {dataIndex: 'dblTotal', text: 'Total', flex: 1, dataType: 'float' , xtype: 'numbercolumn', currencyField: true},
                {dataIndex: 'intTermId', text: 'Term Id', flex: 1, dataType: 'numeric', hidden: true },
                {dataIndex: 'ysnPosted', text: 'Posted', flex: 1, dataType: 'boolean' },
                {dataIndex: 'ysnVoided', text: 'Voided', flex: 1, dataType: 'boolean' },
                {dataIndex: 'intInvoiceSiteId', text: 'Invoice Site Id', flex: 1, dataType: 'numeric', hidden: true },
                {dataIndex: 'intSiteId', text: 'Site Id', flex: 1, dataType: 'numeric', hidden: true },
                {dataIndex: 'intSiteNumber', text: 'Site No', flex: 1, dataType: 'numeric' },
                {dataIndex: 'strSiteDescription', text: 'Site Description', flex: 1, dataType: 'string' },
                {dataIndex: 'strSiteAddress', text: 'Site Address', flex: 1, dataType: 'string' },
                {dataIndex: 'strCity', text: 'City', flex: 1, dataType: 'string' },
                {dataIndex: 'strState', text: 'State', flex: 1, dataType: 'string' },
                {dataIndex: 'strZipCode', text: 'ZipCode', flex: 1, dataType: 'string' },
                {dataIndex: 'strCountry', text: 'Country', flex: 1, dataType: 'string' },
                {dataIndex: 'intInvoiceItemId', text: 'Invoice Item Id', flex: 1, dataType: 'numeric', hidden: true },
                {dataIndex: 'intItemId', text: 'Item Id', flex: 1, dataType: 'numeric', hidden: true },
                {dataIndex: 'strItemNo', text: 'Item No', flex: 1, dataType: 'string' },
                {dataIndex: 'strItemDescription', text: 'Item Description', flex: 1, dataType: 'string' },
                {dataIndex: 'intItemUOMId', text: 'Item UOM Id', flex: 1, dataType: 'numeric', hidden: true },
                {dataIndex: 'strUnitMeasure', text: 'Unit Measure', flex: 1, dataType: 'string' },
                {dataIndex: 'dblQuantity', text: 'Quantity', flex: 1, dataType: 'float' , xtype: 'numbercolumn', currencyField: true},
                {dataIndex: 'dblPrice', text: 'Price', flex: 1, dataType: 'float' , xtype: 'numbercolumn', currencyField: true},
                {dataIndex: 'intContractDetailId', text: 'Contract Detail Id', flex: 1, dataType: 'numeric', hidden: true },
                {dataIndex: 'strContractNumber', text: 'Contract Number', flex: 1, dataType: 'string' },
                {dataIndex: 'intContractSeq', text: 'Contract Sequence', flex: 1, dataType: 'numeric' },
            ]
        }
    ]
    
});