export class VehicleInspection {
    intInspection: number;
    ysnAirCompressorAndLines: boolean;
    ysnBatteryAndConnections: boolean;
    ysnBodyCabDoors: boolean;
    ysnBrakeAccessories: boolean;
    ysnBrakes: boolean;
    ysnCluth: boolean;
    ysnDriveLine: boolean;
    ysnEngine: boolean;
    ysnExhaust: boolean;
    ysnFuelLeak: boolean;
    ysnOilLeak: boolean;
    ysnCoolantLeak: boolean;
    ysnFireExtinguisher: boolean;
    ysnFrontAxle: boolean;
    ysnFuelTanks: boolean;
    ysnHeaterDefroster: boolean;
    ysnHorn: boolean;
    ysnLightsReflectors: boolean;
    ysnGauges: boolean;
    ysnMirrors: boolean;
    ysnMudFlaps: boolean;
    ysnOilPressure: boolean;
    ysnPlacards: boolean;
    ysnRadiator: boolean;
    ysnRearEndAxleStuds: boolean;
    ysnSafetyEquipment: boolean;
    ysnSprings: boolean;
    ysnSteering: boolean;
    ysnTachograph: boolean;
    ysnTanks: boolean;
    ysnTires: boolean;
    ysnTransmission: boolean;
    ysnUnloadingHosesPumps: boolean;
    ysnWheelsRimsLugs: boolean;
    ysnWindows: boolean;
    ysnWindshieldWipers: boolean;
    ysnOthers: boolean;
    strTruckNumber: string;
    ysnNoDefects: boolean;
    strComments: string;
    
    public mapping: Object = {
                                intInspection: 'pk',
                                ysnAirCompressorAndLines: 'boolean',
                                ysnBatteryAndConnections: 'boolean',
                                ysnBodyCabDoors: 'boolean',
                                ysnBrakeAccessories: 'boolean',
                                ysnBrakes: 'boolean',
                                ysnCluth: 'boolean',
                                ysnDriveLine: 'boolean',
                                ysnEngine: 'boolean',
                                ysnExhaust: 'boolean',
                                ysnFuelLeak: 'boolean',
                                ysnOilLeak: 'boolean',
                                ysnCoolantLeak: 'boolean',
                                ysnFireExtinguisher: 'boolean',
                                ysnFrontAxle: 'boolean',
                                ysnFuelTanks: 'boolean',
                                ysnHeaterDefroster: 'boolean',
                                ysnHorn: 'boolean',
                                ysnLightsReflectors: 'boolean',
                                ysnGauges: 'boolean',
                                ysnMirrors: 'boolean',
                                ysnMudFlaps: 'boolean',
                                ysnOilPressure: 'boolean',
                                ysnPlacards: 'boolean',
                                ysnRadiator: 'boolean',
                                ysnRearEndAxleStuds: 'boolean',
                                ysnSafetyEquipment: 'boolean',
                                ysnSprings: 'boolean',
                                ysnSteering: 'boolean',
                                ysnTachograph: 'boolean',
                                ysnTanks: 'boolean',
                                ysnTires: 'boolean',
                                ysnTransmission: 'boolean',
                                ysnUnloadingHosesPumps: 'boolean',
                                ysnWheelsRimsLugs: 'boolean',
                                ysnWindows: 'boolean',
                                ysnWindshieldWipers: 'boolean',
                                ysnOthers: 'boolean',
                                strTruckNumber: 'string',
                                ysnNoDefects: 'boolean',
                                strComments: 'string'
                            }

    public tablename:string = 'vehicleinspection';
}